import express from "express";
import Hello from "./hello";
import Lab5 from "./lab5";
import cors from "cors";
import CourseRoutes from "./courses/routes";
import ModuleRoutes from "./modules/routes";
import "dotenv/config";
const app = express();
app.listen(process.env.PORT || 4000);
app.use(cors());
app.use(express.json());
ModuleRoutes(app);
CourseRoutes(app);
Lab5(app);
Hello(app);
// app.listen(4000);
